### ISSUE TITLE
Add 'path' property to DialogFileSaved<T> event

### ISSUE THREAD

**Issue by Karto1000** [richardhozak/bevy_file_dialog#1]
Right now there doesn't seem to be a way to get the path to where a file was saved in a `DialogFileSaved` event. It seems that you can only access a `file_name: String` and a `result: io::Result<()>`. This would helpful when you need to know where a user saved a file.

**Comment by richardhozak** [comment]
Heya, yes, there is no path field in `DialogFileSaved` struct as it would break compatibility with wasm, you cannot get the path in wasm, just the file name.

There is an escape hatch if you do not care about wasm compatibility, where you can get the path: you can use pick_file dialog and receive `DialogFilePicked` event where you can get `path` field. The downside is, you need to handle the file saving yourself, the easiest way being: `std::fs::write(path, contents)` which you would probably need to handle in bevy async task so it does not block.

What is your exact use case?

**Comment by Karto1000** [comment]
Ah, that makes sense.
I am trying to make the user able to save a file and specify a filename while doing so. After the file is saved, the struct containing the data should have a variable set to the path where the file is saved.
The problem with the `pick_file_dialog` function is that the user cannot actually create a new file (Unless i am missing something), but just select an already existing one, which is not very user friendly.

**Comment by richardhozak** [comment]
Ah, ok, that seems reasonable. I've added path on native platforms and released bevy_file_dialog 0.3.2 containing the changes. Hope it'll be useful!
